### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'vggsoundCategories2Prompts.csv'

### ISSUE THREAD

**Issue by shhuangcoder** [haihuangcode/CMG#1]
hi, nice work, but miss this file, expect you reply,  thx!

**Comment by haihuangcode** [comment]
Thank you for raising this issue. Due to my oversight, some files were not uploaded to the cloud drive. I will update the data folder in the cloud drive soon. Of course, to avoid having you re-download everything, I am directly providing the missing files here. If you have any other issues, please feel free to let me know.
The missing files are:

1. data/vggsound40k/data/vggsoundCategories2Prompts.csv
[vggsoundCategories2Prompts.csv](https://github.com/haihuangcode/CMG/files/13276124/vggsoundCategories2Prompts.csv)

2. data/UCF101/data
[data.zip](https://github.com/haihuangcode/CMG/files/13276129/data.zip)

3. data/AVSBench/data
[data.zip](https://github.com/haihuangcode/CMG/files/13276130/data.zip)

**Comment by shhuangcoder** [comment]
Thx!

**Comment by Lzyin** [comment]
Hello, it seems that some files are still missing, such as "AVSBench_data/Single-source/...".

**Comment by haihuangcode** [comment]
> Hello, it seems that some files are still missing, such as "AVSBench_data/Single-source/...".

Hello, the data we use comes from [AVSBench](https://github.com/OpenNLPLab/AVSBench). The features in our work are directly provided by AVSBench. If you need the complete set of features or data, you can access them at [AVSBench](https://github.com/OpenNLPLab/AVSBench).
