### ISSUE TITLE
Issue with requirements.txt

### ISSUE THREAD

**Issue by tallabon8** [haihuangcode/CMG#14]
Hi,

I've been trying to set up the project using the provided requirements.txt file, but I'm encountering multiple dependency conflicts during the installation process. Specifically, issues with package versions that seem incompatible.

Could you please share the exact requirements.txt file you used to successfully install all dependencies? Alternatively, any guidance on resolving these conflicts would be greatly appreciated.

Thank you for your assistance!

**Comment by haihuangcode** [comment]
Hi, the environment conflicts are mainly caused by the version inconsistency between the numpy library required by bert_embedding and other libraries. As far as I remember, I tried installing bert-embedding first (which requires numpy version 1.14, but using a higher version of numpy doesn't seem to affect its functionality), and then installing the other libraries. Even if the numpy version changes later, the program can still run properly. (Alternatively, you could try installing the torch-related and other libraries first, and then install bert-embedding afterward. That might work as well.)

Currently, the environment where I can run CMG is as follows:
torch==1.13.1
torchaudio==0.13.1
torchvision==0.14.0
numpy==1.21.6
bert-embedding==1.0.1
